version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    container_name: solar_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: solar_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: solar_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio_root_user
      MINIO_ROOT_PASSWORD: Minio1234!
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  redis:
    image: redis:7-alpine
    container_name: solar_redis
    command: redis-server --requirepass redis_password --maxmemory 128mb --maxmemory-policy allkeys-lru --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build: .
    container_name: solar_api
    command: ["node", "dist/app.js"]
    environment:
      DISABLE_CRON: "1"
      PORT: "3000"
      USE_QUEUE: "true"
      DATABASE_URL: "postgresql://admin:password123@postgres:5432/solar_db?schema=public"
      MINIO_ENDPOINT: "http://minio:9000"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_PASSWORD: redis_password
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - minio
      - redis

  worker:
    build: .
    container_name: solar_worker
    command: ["node", "dist/worker.js"]
    environment:
      WORKER_PORT: "3001"
      USE_QUEUE: "true"
      DATABASE_URL: "postgresql://admin:password123@postgres:5432/solar_db?schema=public"
      MINIO_ENDPOINT: "http://minio:9000"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_PASSWORD: redis_password
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - minio
      - redis

volumes:
  postgres_data:
  minio_data:
  redis_data:
